# Generated by Django 3.0.3 on 2020-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, default='0412312312', max_length=10),
            preserve_default=False,
        ),
    ]
