# Generated by Django 3.0.3 on 2020-03-04 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_job', '0002_auto_20200302_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Phone must only contain numbers')]),
        ),
    ]
